#Nuestro primer pipeline

name: Revision codigo

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Review
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - run: flutter pub get
      name: Obtener paquetes
    
    - run: flutter format .
      name: Formato de codigo
    
    - run: flutter analyze
      name: Analisis de flutter
    
    - run: flutter test
      name: flutter Test
